### ISSUE TITLE
Esc firmware update Freezes

### ISSUE THREAD

**Issue by Propwosh** [FETtec/ESC-Configurator#13]
The esc firmware update freezes, if you have the newest firmware (1.3RC45y) on your FC. 

I had to downgrade to (1.3RC40o) and after that the esc firmware update worked.

I'm using macOS

**Comment by lichtl** [comment]
Hmm I am unable to replicate that. Do you have some more details (OS version) etc. Also did you tried to restart the app or your Mac?

**Comment by Propwosh** [comment]
macOS Sierra 10.12.6

Yes, I tried to restart the software. I also removed and installed it again. 

I tried different ways to connect the usb, battery and the software. 

I also re-flashed the fc with the newest firmware a few times. One time after that, i got the esc number 1 flashed, but after that it did freeze on number two. I also tried to flash only 1 esc at a time, but it did freeze (tried that also with every esc). 

Also the "settings" and "telemetry" -tabs made the software to freeze. 


At last i flashed the fc with the older firmware and restarted fettec configurator and everything worked like it should (also the telemetry and settings tabs) 

After that I reflashed the fc with the newest version without a problem. But I haven't connected to the esc configurator after that.

**Comment by pejer** [comment]
I have the same problem. With the latest firmware - 1.3RC45y - I can't connect to the esc, with kiss-fc-passthru. Tried with Linux & Windows. 


After I downgrade the fc to the previous version , no problem. 

I have your fc & your 35a esc, v1.0.

**Comment by lichtl** [comment]
> I have the same problem. With the latest firmware - 1.3RC45y - I can't connect to the esc, with kiss-fc-passthru. Tried with Linux & Windows.
> 
> After I downgrade the fc to the previous version , no problem.
> 
> I have your fc & your 35a esc, v1.0.

This doesn't seem to be the same problem. Above one is about freeze on flash. Your seems to be a problem with connectivity. Could you please provide some more details and ideally in a new issue) Provide details about your settings (mainly serial ports) what hardware is connected to the serial ports (ImpulseOSD/WolfOSD/DJI Airunit/GPS etc)

Thanks

**Comment by pejer** [comment]
@Propwosh my problem was that I had disabled serial5. After enabling that - it all worked perfectly. I think your problem is different, hope you manage to solve it.

**Comment by lichtl** [comment]
I am unable to replicate this behavior. Tried on 3 different Macs (Macbook Pro 2018 - Catalina / Macbook Pro 2010 - High Sierra / Macbook Pro 2019 - Catalina) and also other testes using Macs  are unable to replicate this.

**Comment by EFBok** [comment]
Hi There,

I would like to add that I had a similar problem. I updated the ESC and it stopped halfway. I thought I had bricked it and looked all over for a solution.

I have the Fettec FC and the Fettec 45A ESC. The problem was that I had a GPS unit connected to the FC and I assume that was causing communication issues with the ESC. Once I unplugged the GPS from the FC the flash was successful.

Hope this helps
Cheers

**Comment by sreese4u** [comment]
> I have the Fettec FC and the Fettec 45A ESC. The problem was that I had a GPS unit connected to the FC and I assume that was causing communication issues with the ESC. Once I unplugged the GPS from the FC the flash was successful.

You made my day. This was exactly my issue. Thank you!
@lichtl Please fix. This bug is really strange.
