### ISSUE TITLE
Unable to connect to ESC with 1.3RC45y

### ISSUE THREAD

**Issue by pejer** [FETtec/ESC-Configurator#14]
Software:
Kiss GUI v2.0.27
FETTec Configurator 0.1.23

Hardware:
FETtec KISS FC
FETtec 35AMP 4-in-1 ESC v1.0
DJI Caddx Vista
TBS Nano receiver

Serial port configuration:
Serial1 KissProtocol/OSD 
Serial2 Receiver
Serial3: DJI-MSP
Serial5: Disabled

PROBLEM:
With 1.3RC45y, I cannot connect to the ESC at all. This happens on both Windows and Linux.

If I downgrade the FC to 1.3RC40o then I can connect to the ESC, upgrade it, configure it etc.

**So I've tested 1.3RC40o and 1.3RC45y, both with my configs and just flashed and 1.3RC45y never works while 1.3RC40o works regardless of config.**

Test 1:
FC: 1.3RC45y with my config
No connection at all to ESC.

Test 2:
FC: 1.3RC40o no config changes, just flashed
Connection to ESC works, can upgrade.

Test 3:
FC: 1.3RC40o my configs loaded
Connection to ESC works, can upgrade, save etc.

Test4:
FC: 1.3RC45y no config changes, just flashed
No connection to ESC.

Could be firmware problem also.

I don't know if there are any logs somewhere that I can attach - sorry.

**Comment by lichtl** [comment]
Is there any reason you disabled serial5? This has to be on "ESC TLM/OneWire". Could you please change this and test again.

**Comment by pejer** [comment]
Why I disabled serial5? Because I'm an idiot....?

You're absolutely right - enabling Serial5 made it work. I didn't know that I needed to enable it - everything seemed to work without it so I just disabled it, thinking it was a smart thing to do.

I was wrong, clearly.

Thanks for helping out, sorry that I bothered you with this dumb problem.

**Comment by lichtl** [comment]
all good :-)
