### ISSUE TITLE
Betaflight/Fettec ESC  motor direction changes

### ISSUE THREAD

**Issue by Ayougo** [FETtec/ESC-Configurator#5]
Unable to reverse motor directions as esc's are not recognized during betaflight passthrough OR Kiss passthrough. I used a Kiss V2 board connected to the Fettec ESC when the betaflight passthrough failed. The result of trying to connect to the esc's was the same...

**Comment by lichtl** [comment]
Do you have some more details? 

Was the ESC connected to the TX pad and the config was properly applied? on the V2 which protocol was set and which pad was used (if set to Onewire it require TLM pad connected to Motor PIN6 instead of the default TLM pad).
